# Generated by Django 5.2 on 2025-04-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='folder',
            table='rep_folder',
        ),
        migrations.AlterModelTable(
            name='resource',
            table='rep_resource',
        ),
    ]
