# Generated by Django 5.2 on 2025-04-12 16:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_alter_folder_table_alter_resource_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='logical_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='logical_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=40, unique=True),
        ),
    ]
