# Generated by Django 5.2 on 2025-04-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_alter_folder_logical_id_alter_resource_logical_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_folder_name'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('folder', 'name'), name='unique_resource_folder_name'),
        ),
    ]
