# Generated by Django 5.2 on 2025-04-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_folder_unique_folder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
